# Generated by Django 5.1.5 on 2025-03-13 17:22

import app_admin.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('short_description', models.CharField(max_length=200, verbose_name='Краткое описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(regex='^[а-яА-ЯёЁ\\s]+$')], verbose_name='Имя')),
                ('last_name', models.CharField(max_length=250, validators=[django.core.validators.RegexValidator(regex='^[а-яА-ЯёЁ\\s]+$')], verbose_name='Фамилия')),
                ('mobile', models.CharField(max_length=11, validators=[app_admin.models.validate_russian_mobile], verbose_name='Мобильный телефон')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='Электронная почта')),
                ('address', models.CharField(blank=True, max_length=40, null=True, verbose_name='Адрес')),
                ('profile_image', models.ImageField(blank=True, default='profile_images/default.jpg', null=True, upload_to='profile_images/', verbose_name='Фото профиля')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Псевдоним')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('short_description', models.TextField(verbose_name='Краткое описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_on_sale', models.BooleanField(default=False, verbose_name='По акции')),
                ('discount', models.IntegerField(blank=True, null=True, verbose_name='Скидка (%)')),
                ('discount_start_date', models.DateField(blank=True, null=True, verbose_name='Дата начала акции')),
                ('discount_end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания акции')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_admin.productcategory', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
